# Generated by Django 4.2.6 on 2023-10-31 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
